### ISSUE TITLE
js not initializing

### ISSUE THREAD

**Issue by cloudcoderuwu** [benmurden/django-intl-tel-input#1]
I've checked that jquery is included before init.js, but the js is still not initializing properly. The widget works if I run the init code from the console, but not after the page load.

**Comment by benmurden** [comment]
Does it work if jQuery is initialized in the head? It goes against the load-everything-in-the-body philosophy, but I have noticed that the `jQuery` global is not available if you don't.

**Comment by cloudcoderuwu** [comment]
Yeah, I have jQuery loaded in the head before init.js is loaded (also in the head).

**Comment by benmurden** [comment]
Ah, I see. If the `init.js` is in the head, it won't find the inputs - it doesn't wait for the entire document to be ready. Either remove the `{{ form.media.js }}` tag, which will cause those assets to be inserted immediately after the widget, or place the tag in a javascript block at the end of your document.

This is certainly something that can be improved with the documentation. Apologies for that.

**Comment by cloudcoderuwu** [comment]
Ah, well that is a bit of an issue because I am trying to use it in the admin where you don't have much control over those things.

**Comment by benmurden** [comment]
Admin templates are fiddly, but can be overridden or replaced.
https://docs.djangoproject.com/en/1.9/ref/contrib/admin/#overriding-vs-replacing-an-admin-template

Alternatively, if you must have `{{ form.media.js }}` in the head, try wrapping it in a `jQuery(document).ready();` block.

**Comment by cloudcoderuwu** [comment]
Ah, so obvious! I'll work with the latter, thanks!

**Comment by benmurden** [comment]
No problem! I'll go ahead and close this issue. I assume this solves the other issue, too, but if not, let me know.
