### ISSUE TITLE
Allow setting placeholder text in generated widget

### ISSUE THREAD

**Issue by sureshvv** [benmurden/django-intl-tel-input#10]
Seems to always go to 123456789.

**Comment by benmurden** [comment]
I'm not sure I understand. Could you illustrate with an example? Expected vs. actual?

Intl-tel-input does already, as far as I know, add a locale appropriate placeholder when it is initialized.

**Comment by sureshvv** [comment]
Support placeholder in one of two ways:

       contact_no = forms.CharField(label="Contact No", required=False,
                                    widget=IntlTelInputWidget(`
                                        default_code='in',
                                        preferred_countries=['in']),
                                    placeholder="Ten digit mobile number")

or

       contact_no = forms.CharField(label="Contact No", required=False,
                                    widget=IntlTelInputWidget(
                                       default_code='in',
                                       preferred_countries=['in'],
                                       attrs=dict(placeholder="Ten digit mobile number"))

**Comment by benmurden** [comment]
I think I understand. You want to override the provided placeholder text generated by intl-tel-input, is that right?

The plugin appears to support this, so I'll look into translating widget invocation appropriately.

**Comment by sureshvv** [comment]
Great!

**Comment by benmurden** [comment]
@sureshvv Should be fixed in 0.1.5. Use your second example and set the placeholder in the input `attrs`.

**Comment by sureshvv** [comment]
Not working for me. Debugging.

**Comment by sureshvv** [comment]
Works! Thank you!!

**Comment by benmurden** [comment]
Great!
