### ISSUE TITLE
_format_value error

### ISSUE THREAD

**Issue by pedrodcb** [benmurden/django-intl-tel-input#11]
Similar to this issue:

https://github.com/pbucher/django-bootstrap-datepicker/issues/9

AttributeError: 'IntlTelInputWidget' object has no attribute '_format_value' in recent Django versions.

I fixed it on my local version by changing `_format_value` to `format_value` on line 58 of widgets.py file.

**Comment by benmurden** [comment]
Thanks for the info. If it's that simple, I'd accept a PR. Would need to extend the test matrix.
