### ISSUE TITLE
How to enable auto_geo_ip

### ISSUE THREAD

**Issue by svb0866** [benmurden/django-intl-tel-input#15]
Dear Benmurden,

Thank you for the widget. It helped me a lot. I was wondering how do I enable the auto_geo_ip. 

Thanks.

Warm Regards,
svb

**Comment by benmurden** [comment]
We no longer provide a default implementation of `auto_geo_ip`, as discussed in #14.

To implement your own, invoke the widget with `use_default_init=False` as in the following example, and provide your own initialization script after `{{ form.media.js }}`.

```Python
class MyForm(forms.Form):
    tel_number = forms.CharField(widget=IntlTelInputWidget(
        use_default_init=False
    ))
```
