### ISSUE TITLE
ImportError: cannot import name 'force_text' from 'django.utils.encoding'

### ISSUE THREAD

**Issue by afusaru** [benmurden/django-intl-tel-input#18]
Can't use it with python 3.10.7, Django 4.1.2.

Since Django 4.0, there is not force_text but force_str, so I've changed intl_tel_input/widgets.py:

Line 5 became: from django.utils.encoding import force_str
Line 65 became: final_attrs['value'] = force_str(self.format_value(value))

**Comment by benmurden** [comment]
Thanks for the report, is this something that would be easy to put into a PR while maintaining some backwards compatibility with supported versions of Django?

**Comment by afusaru** [comment]
I played around a bit, the only modifications I made were to import force_str and updated to the last version of intl-tel-input. And it seems to work, so no major changes.

**Comment by benmurden** [comment]
Closed by #19

**Comment by panatale1** [comment]
@benmurden while you updated it for Django 3.0+, you never rebuilt the package, so PyPI is still serving a package that breaks with newer versions of Django. Would it be possible for you to rebuild it and upload it, or would it be better for me to fork it?

**Comment by benmurden** [comment]
@panatale1 Thanks for the report. It has been some time since I did anything with Python, but I will take a look and see if I can get a new package up.

Update: new version has been uploaded here https://pypi.org/project/django-intl-tel-input/0.4.0/
