### ISSUE TITLE
Development status?

### ISSUE THREAD

**Issue by panatale1** [benmurden/django-intl-tel-input#20]
@benmurden Is this project abandoned, or will there be updates for Django 4.2+?

**Comment by benmurden** [comment]
I am no longer actively working with Python and Django, but I am happy to review and merge PRs.

**Comment by panatale1** [comment]
Thanks, @benmurden! I might have an update in the coming weeks, something is preventing a field using this widget from functioning properly, but I haven't had the time to dive in and figure it out just yet
