### ISSUE TITLE
how can i get country telephone code in form data?

### ISSUE THREAD

**Issue by hungphamvn** [benmurden/django-intl-tel-input#6]

**Comment by benmurden** [comment]
The default widget grabs the full number, which includes the country code. If you need the code separately, you can add some Javascript using the public methods available in intl-tel-input.

https://github.com/jackocnr/intl-tel-input#public-methods

**Comment by hungphamvn** [comment]
thank you for your response,
i have another issue is it can't auto setup initial country, any suggestion?
thank you,

**Comment by benmurden** [comment]
It would probably be best to set the initial value using [pygeoip](https://pypi.python.org/pypi/pygeoip), since the freegeoip method isn't too reliable.
