### ISSUE TITLE
Does not seem to be possible to have 2 of these fields on the same form

### ISSUE THREAD

**Issue by sureshvv** [benmurden/django-intl-tel-input#9]
Values not getting transferred to/from the hidden field.

Can someone confirm?

**Comment by benmurden** [comment]
Thanks for the report. I'll take a look as soon as I can.

**Comment by sureshvv** [comment]
Will be happy to help fix/test/debug once you confirm that it is a  problem.

**Comment by sureshvv** [comment]
I think the bug is in init.js. When there is more than one widget in a form, the control selected is always the last one. Unfortunately my javascript fu is a bit weak.

**Comment by benmurden** [comment]
I have written a failing test and will work on a fix.

**Comment by benmurden** [comment]
@sureshvv Please try the latest release and let me know if everything is working correctly for you.

**Comment by sureshvv** [comment]
0.1.4 is working better!

In init.js realInput is now being set to the proper hidden input field.

But the value is not getting copied from it.

Works when there is only 1 control.

Digging some more!

**Comment by sureshvv** [comment]
wait a minute. It may be working.

**Comment by benmurden** [comment]
I'll close this out now, but if you still have issues, feel free to reopen.
